In [1]:
import pandas as pd

In [2]:
df_vendas = pd.read_excel('../data/dados_ecommerce.xlsx', sheet_name='vendas_olist')

In [3]:
df_vendas['produto_categoria'] = df_vendas['produto_categoria'].fillna('Não Informado')

In [4]:
df_vendas['cliente_cidade'] = df_vendas['cliente_cidade'].fillna('Desconhecido')

In [5]:
df_vendas = df_vendas.dropna(subset=['preco'])

In [6]:
df_vendas.isna().sum()

id_pedido            0
data_compra          0
produto_categoria    0
preco                0
frete                0
cliente_cidade       0
avaliacao_score      0
dtype: int64

In [7]:
df_vendas.groupby('produto_categoria')["preco"].sum()

produto_categoria
Não Informado              968.13
beleza_saude              7890.66
esporte_lazer             3700.17
informatica_acessorios    7482.96
moveis_decoracao          4006.52
utilidades_domesticas     7574.36
Name: preco, dtype: float64

In [8]:
faturamente_categoria=df_vendas.groupby('produto_categoria')["preco"].sum().sort_values(ascending=False)

In [9]:
faturamento_caterogia = faturamente_categoria
faturamento_caterogia

produto_categoria
beleza_saude              7890.66
utilidades_domesticas     7574.36
informatica_acessorios    7482.96
moveis_decoracao          4006.52
esporte_lazer             3700.17
Não Informado              968.13
Name: preco, dtype: float64

In [10]:
df_vendas.groupby('produto_categoria')['preco'].agg(['sum','mean','count']).sort_values(by='sum',ascending=False)

                            sum        mean  count
produto_categoria
beleza_saude            7890.66  151.743462     52
utilidades_domesticas   7574.36  120.227937     63
informatica_acessorios  7482.96  143.903077     52
moveis_decoracao        4006.52  114.472000     35
esporte_lazer           3700.17  137.043333     27
Não Informado            968.13   88.011818     11

In [11]:
analise_vendas = df_vendas.groupby('produto_categoria')['preco'].agg(['sum','mean','count']).sort_values(by='sum',ascending=False)

In [12]:
analise_cidade = df_vendas.groupby('cliente_cidade')['preco'].agg(['sum','count']).sort_values(by='sum', ascending=False)
analise_cidade

                     sum  count
cliente_cidade
sao paulo       12795.33     79
rio de janeiro   7441.43     58
Desconhecido     3600.56     27
belo horizonte   2559.44     23
curitiba         2486.31     25
porto alegre     1570.85     15
salvador         1168.88     13

In [13]:

mapa_ceps = {
    'sao paulo': '01001-000',
    'rio de janeiro': '20020-000',
    'belo horizonte': '30110-000',
    'curitiba': '80010-000',
    'porto alegre': '90010-000',
    'salvador': '40010-000',
    'desconhecido': '00000-000'
}

df_vendas['cliente_cep'] = df_vendas['cliente_cidade'].map(mapa_ceps)

df_vendas['cliente_cep'] = df_vendas['cliente_cep'].str.replace('-', '')

df_vendas['cliente_cidade'] = df_vendas['cliente_cidade'].str.title()

df_vendas.head()

,id_pedido,data_compra,produto_categoria,preco,frete,cliente_cidade,avaliacao_score,cliente_cep
0,req_221958,2025-01-01 00:00:00,moveis_decoracao,47.71,26.59,Sao Paulo,5,01001000
1,req_771155,2025-01-01 01:00:00,informatica_acessorios,151.67,22.43,Sao Paulo,3,01001000
2,req_231932,2025-01-01 02:00:00,utilidades_domesticas,176.61,32.71,Belo Horizonte,3,30110000
3,req_465838,2025-01-01 03:00:00,informatica_acessorios,47.65,26.79,Curitiba,3,80010000
4,req_359178,2025-01-01 04:00:00,beleza_saude,71.93,30.45,Porto Alegre,4,90010000